language: php

php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - composer install --no-interaction --dev --prefer-dist

script:
  - php vendor/bin/phpunit --coverage-clover build/coverage.clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
